### ISSUE TITLE
Fix not reconnecting after connection lost

### ISSUE THREAD

**Issue by Bigomby** [Bigomby/yeelight-plugin#1]
Sometimes when the server lost the connection with the bulb does not try to recover.

**Comment by jsdario** [comment]
Hey! (I am watching the repo in case you need help) I was checking  little bit your source, so maybe I cannot give a proper inside, but – maybe a basic `setInverval` can help you out.

Plus, Is the "re-scan" button nor working on the dashboard? May I can help a bit over there?
Best
